# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\"(\n\x10\x43haracterRequest\x12\x14\n\x0c\x63haracter_id\x18\x01 \x01(\x05\"\xa3\x01\n\x11\x43haracterResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07species\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\x0e\n\x06origin\x18\x06 \x01(\t\x12\x10\n\x08location\x18\x07 \x01(\t\x12\r\n\x05image\x18\x08 \x01(\t\x12\x10\n\x08\x65pisodes\x18\t \x03(\t2K\n\x0c\x43\x61\x63heService\x12;\n\x10GetCharacterById\x12\x11.CharacterRequest\x1a\x12.CharacterResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHARACTERREQUEST']._serialized_start=15
  _globals['_CHARACTERREQUEST']._serialized_end=55
  _globals['_CHARACTERRESPONSE']._serialized_start=58
  _globals['_CHARACTERRESPONSE']._serialized_end=221
  _globals['_CACHESERVICE']._serialized_start=223
  _globals['_CACHESERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
