version: '3'

services:
  cache-server-classic:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data

  cache-server-partitioned:
    build: .
    ports:
      - "5001:5000"
    environment:
      - PARTITIONED=true
    volumes:
      - ./data:/app/data

  cache-server-replicated:
    build: .
    ports:
      - "5002:5000"
    environment:
      - REPLICATED=true
    volumes:
      - ./data:/app/data

  redis-cache-classic:
    image: redis
    ports:
      - "6379:6379"

  redis-cache-partitioned:
    image: redis
    ports:
      - "6380:6379"

  redis-cache-replicated:
    image: redis
    ports:
      - "6381:6379"
